on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - .git*
      - "**.md"
      - "library.properties"
      - "library.json"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - .git*
      - "**.md"
      - "library.properties"
      - "library.json"

jobs:
  build-wifi:
    name: "Build Test (WiFi): ${{matrix.board.arch}}:${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - vendor: esp8266
            arch: esp8266
            name: generic
          - vendor: esp32
            arch: esp32
            name: esp32
          # TODO: temporary disabled because of compile error of FastLED
          # - vendor: esp32
          #   arch: esp32
          #   name: esp32s3
          - vendor: esp32
            arch: esp32
            name: esp32c3
          # TODO: temporary disabled because of compile error of FastLED (Error: invalid offset, value too big)
          # - vendor: rp2040
          #   arch: rp2040
          #   name: rpipicow
          # - vendor: rp2040
          #   arch: rp2040
          #   name: rpipico2w
        include:
          - index: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            board:
              vendor: esp8266
          - index: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            board:
              vendor: esp32
          # - index: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          #   board:
          #     vendor: rp2040
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples/WiFi
          libraries: |
            - source-path: ./
            - name: ArxContainer
            - name: ArxTypeTraits
            - name: PollingTimer
            - name: WiFi
            - name: FastLED
          verbose: true

  build-wifinina:
    name: "Build Test (WiFiNINA): ${{matrix.board.arch}}:${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - vendor: arduino
            arch: megaavr
            name: uno2018
          - vendor: arduino
            arch: samd
            name: mkrvidor4000
          - vendor: arduino
            arch: samd
            name: mkrwifi1010
          - vendor: arduino
            arch: samd
            name: nano_33_iot
        include:
          - index: https://downloads.arduino.cc/packages/package_index.json
            board:
              vendor: arduino
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples/WiFi/receiver
            - examples/WiFi/sender
          libraries: |
            - source-path: ./
            - name: ArxContainer
            - name: ArxTypeTraits
            - name: PollingTimer
            - name: WiFiNINA
            - name: VidorPeripherals
            - name: FastLED
          verbose: true

  build-wifis3:
    name: "Build Test (WiFiS3): ${{matrix.board.arch}}:${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - vendor: arduino
            arch: renesas_uno
            name: unor4wifi
        include:
          - index: https://downloads.arduino.cc/packages/package_index.json
            board:
              vendor: arduino
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples/WiFi/receiver
            - examples/WiFi/sender
          libraries: |
            - source-path: ./
            - name: ArxContainer
            - name: ArxTypeTraits
            - name: PollingTimer
          verbose: true

  build-ethernet:
    name: "Build Test (Ethernet): ${{matrix.board.arch}}:${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - vendor: arduino
            arch: avr
            name: uno
          - vendor: arduino
            arch: megaavr
            name: uno2018
          - vendor: arduino
            arch: samd
            name: mkrvidor4000
          - vendor: arduino
            arch: samd
            name: mkrwifi1010
          - vendor: arduino
            arch: samd
            name: mkr1000
          - vendor: arduino
            arch: samd
            name: nano_33_iot
          - vendor: esp8266
            arch: esp8266
            name: generic
          - vendor: esp32
            arch: esp32
            name: esp32
          - vendor: esp32
            arch: esp32
            name: esp32s3
          - vendor: esp32
            arch: esp32
            name: esp32c3
          - vendor: rp2040
            arch: rp2040
            name: rpipicow
          - vendor: rp2040
            arch: rp2040
            name: rpipico2w
          # - vendor: teensy
          #   arch: avr
          #   name: teensy35
          # - vendor: teensy
          #   arch: avr
          #   name: teensy36
          # - vendor: teensy
          #   arch: avr
          #   name: teensy41
        include:
          - index: https://downloads.arduino.cc/packages/package_index.json
            board:
              vendor: arduino
          - index: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            board:
              vendor: esp8266
          - index: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            board:
              vendor: esp32
          - index: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
            board:
              vendor: rp2040
          # - index: https://www.pjrc.com/teensy/package_teensy_index.json
          #   board:
          #     vendor: teensy
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples/Ethernet/receiver
            - examples/Ethernet/sender
          libraries: |
            - source-path: ./
            - name: ArxContainer
            - name: ArxTypeTraits
            - name: PollingTimer
            - name: Ethernet
            - name: FastLED
          verbose: true

  build-eth:
    name: "Build Test (ETH): ${{matrix.board.arch}}:${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - vendor: esp32
            arch: esp32
            name: esp32
          # TODO: temporary disabled because of compile error of FastLED
          # - vendor: esp32
          #   arch: esp32
          #   name: esp32s3
          - vendor: esp32
            arch: esp32
            name: esp32c3
        include:
          - index: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            board:
              vendor: esp32
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples/ETH
          libraries: |
            - source-path: ./
            - name: ArxContainer
            - name: ArxTypeTraits
            - name: PollingTimer
            - name: FastLED
          verbose: true

  build-etherenc:
    name: "Build Test (EtherENC): ${{matrix.board.arch}}:${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          # temporarily disabled due to memory shortage in `sender` example
          # - vendor: arduino
          #   arch: avr
          #   name: uno
          # TODO: temporary disabled because of compile error of FastLED
          # - vendor: arduino
          #   arch: megaavr
          #   name: uno2018
          # TODO: temporary disabled because of compile error of FastLED
          # - vendor: arduino
          #   arch: samd
          #   name: mkrvidor4000
          # - vendor: arduino
          #   arch: samd
          #   name: mkrwifi1010
          # - vendor: arduino
          #   arch: samd
          #   name: mkr1000
          # - vendor: arduino
          #   arch: samd
          #   name: nano_33_iot
          - vendor: esp8266
            arch: esp8266
            name: generic
          - vendor: esp32
            arch: esp32
            name: esp32
          # TODO: temporary disabled because of compile error of FastLED
          # - vendor: esp32
          #   arch: esp32
          #   name: esp32s3
          - vendor: esp32
            arch: esp32
            name: esp32c3
          # TODO: temporary disabled because of compile error of FastLED (Error: invalid offset, value too big)
          # - vendor: rp2040
          #   arch: rp2040
          #   name: rpipicow
          # - vendor: rp2040
          #   arch: rp2040
          #   name: rpipico2w
        include:
          # TODO: temporary disabled because of compile error of FastLED for SAMD
          # - index: https://downloads.arduino.cc/packages/package_index.json
          #   board:
          #     vendor: arduino
          - index: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            board:
              vendor: esp8266
          - index: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            board:
              vendor: esp32
          # - index: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          #   board:
          #     vendor: rp2040
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples/EthernetENC/receive_fastled
            - examples/EthernetENC/receiver
            - examples/EthernetENC/send_receive
            - examples/EthernetENC/sender
          libraries: |
            - source-path: ./
            - name: ArxContainer
            - name: ArxTypeTraits
            - name: PollingTimer
            - name: FastLED
            - source-url: https://github.com/JAndrassy/EthernetENC.git
          verbose: true

  build-multi:
    name: "Build Test (Multiple): ${{matrix.board.arch}}:${{matrix.board.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - vendor: esp32
            arch: esp32
            name: esp32
          - vendor: esp32
            arch: esp32
            name: esp32s3
          - vendor: esp32
            arch: esp32
            name: esp32c3
        include:
          - index: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            board:
              vendor: esp32
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
      - name: compile example sketchs
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
              source-url: ${{matrix.index}}
          sketch-paths: |
            - examples/Multiple
          libraries: |
            - source-path: ./
            - name: ArxContainer
            - name: ArxTypeTraits
            - name: PollingTimer
            - name: WiFi
            - name: Ethernet
          verbose: true
